# Generated by Django 2.1rc1 on 2019-12-02 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20191202_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OftyUserWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_enable', models.BooleanField(default=True)),
                ('mon_start_h', models.IntegerField(default=9)),
                ('mon_start_m', models.IntegerField(default=0)),
                ('mon_stop_h', models.IntegerField(default=21)),
                ('mon_stop_m', models.IntegerField(default=0)),
                ('tue_enable', models.BooleanField(default=True)),
                ('tue_start_h', models.IntegerField(default=9)),
                ('tue_start_m', models.IntegerField(default=0)),
                ('tue_stop_h', models.IntegerField(default=21)),
                ('tue_stop_m', models.IntegerField(default=0)),
                ('wed_enable', models.BooleanField(default=True)),
                ('wed_start_h', models.IntegerField(default=9)),
                ('wed_start_m', models.IntegerField(default=0)),
                ('wed_stop_h', models.IntegerField(default=21)),
                ('wed_stop_m', models.IntegerField(default=0)),
                ('thu_enable', models.BooleanField(default=True)),
                ('thu_start_h', models.IntegerField(default=9)),
                ('thu_start_m', models.IntegerField(default=0)),
                ('thu_stop_h', models.IntegerField(default=21)),
                ('thu_stop_m', models.IntegerField(default=0)),
                ('fri_enable', models.BooleanField(default=True)),
                ('fri_start_h', models.IntegerField(default=9)),
                ('fri_start_m', models.IntegerField(default=0)),
                ('fri_stop_h', models.IntegerField(default=21)),
                ('fri_stop_m', models.IntegerField(default=0)),
                ('sat_enable', models.BooleanField(default=False)),
                ('sat_start_h', models.IntegerField(default=9)),
                ('sat_start_m', models.IntegerField(default=0)),
                ('sat_stop_h', models.IntegerField(default=21)),
                ('sat_stop_m', models.IntegerField(default=0)),
                ('sun_enable', models.BooleanField(default=False)),
                ('sun_start_h', models.IntegerField(default=9)),
                ('sun_start_m', models.IntegerField(default=0)),
                ('sun_stop_h', models.IntegerField(default=21)),
                ('sun_stop_m', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='oftyuserrentlord',
            name='user',
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='company_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='metro',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='nickname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='phone',
            field=models.TextField(default='02'),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='phone2',
            field=models.TextField(default='03'),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='rent_commentary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='site',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='oftyuser',
            name='sklad',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='OftyUserRentLord',
        ),
    ]
