# Generated by Django 3.0.2 on 2020-02-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
